version: "3.9"  # optional since v1.27.0
services:
  api:
    build: .
    ports:
      - "4443:443"
    links:
      - db
      - redis
  db:
    image: scylladb/scylla-nightly:latest
    ports:
      - "8000:8000"
    command: "--alternator-port 8000 --alternator-write-isolation always"
  redis:
    platform: linux/x86_64
    build: 
      context: ./redis-server
    ports:
      - "4444:443"
